- id: "account"
  upstream:
    preserve_host: true
    url: "http://kratos:4433"
    strip_path: /api/v2/accounts
  match:
    url: "http://127.0.0.1:8080/api/v2/accounts/<**>"
    methods:
      - POST
      - GET
      - PUT
      - PATCH
      - DELETE
  authenticators:
    - handler: cookie_session
  mutators:
    - handler: header
  authorizer:
    handler: allow
  errors:
    - handler: redirect
      config:
        to: http://127.0.0.1:4200/auth/login
