- id: "backend"
  upstream:
    preserve_host: true
    url: "http://backend:8000"
  match:
    url: "http://localhost:8080/api/v2/auth/<**>"
    methods:
      - POST
      - GET
      - PUT
      - PATCH
      - DELETE
  authenticators:
    - handler: noop
  mutators:
    - handler: noop
  authorizer:
    handler: allow